"""
CLI action handlers for Outrider lifecycle management.

`remyxai outrider init` installs the Outrider GitHub Action on a
target repo by talking to the GitHub API directly (via `gh api` and
`gh secret set` shellouts). Nothing in the customer's local working
tree is mutated — branch creation, file write, and PR open all
happen server-side.

Alternative to the GitHub-App-based install flow (engine.remyx.ai's
provision-action endpoint) for orgs that can't or won't grant a
third-party App access.

Side-effect ordering (rollback-safe): reversible mutations first,
secrets last. If anything fails after the first mutation, the
created branch + PR are rolled back. Secrets are NOT rolled back —
if secret-set fails, we leave any successfully-set secret in place
and tell the operator to clean up manually rather than risk
overwriting a pre-existing value with whatever-was-there-before
(which `gh secret list` won't reveal).
"""
from __future__ import annotations

import base64
import json
import logging
import os
import re
import shutil
import subprocess
from importlib import resources
from typing import Optional

import click

from remyxai.api.interests import create_interest, get_interest

logger = logging.getLogger(__name__)

DEFAULT_BRANCH_NAME = "install-outrider"
WORKFLOW_PATH = ".github/workflows/outrider.yml"
PR_TITLE = "Install Outrider — weekly arXiv → draft PR scout"
PR_BODY_TEMPLATE = """\
Adds [remyxai/outrider](https://github.com/remyxai/outrider) on a weekly Monday-14:00-UTC schedule (with `workflow_dispatch` for manual triggering). Outrider queries engine.remyx.ai for a paper recommendation against this repo's ResearchInterest, then opens a draft PR (or Issue) wiring the paper's contribution into an existing call site.

**What was installed:**

- `.github/workflows/outrider.yml` — weekly cron + manual dispatch
- Repo secret `REMYX_API_KEY` — engine.remyx.ai token (set by the CLI)
- Repo secret `ANTHROPIC_API_KEY` — Anthropic console token (set by the CLI)

**Research interest**: `{interest_id}`

Generated by `remyxai outrider init`. Review the workflow, merge when ready.
"""

UUID_RE = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-"
    r"[0-9a-f]{4}-[0-9a-f]{12}$",
    re.IGNORECASE,
)


# ─── repo detection (read-only, doesn't mutate working tree) ──────────────

def _detect_github_repo_from_cwd() -> Optional[str]:
    """Parse `origin` remote URL of the cwd's git repo, if any.

    Used only for the default value of --repo. Walking up to find .git
    is OK; we do not touch the working tree.
    """
    try:
        out = subprocess.check_output(
            ["git", "remote", "get-url", "origin"],
            text=True, stderr=subprocess.DEVNULL,
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None
    url = out[:-4] if out.endswith(".git") else out
    m = re.match(r"git@github\.com:([\w.-]+/[\w.-]+)$", url)
    if m:
        return m.group(1)
    m = re.match(r"https?://github\.com/([\w.-]+/[\w.-]+)$", url)
    if m:
        return m.group(1)
    return None


# ─── gh CLI helpers ────────────────────────────────────────────────────────

def _gh_available() -> bool:
    return shutil.which("gh") is not None


def _gh_authenticated() -> bool:
    """Return True if `gh` can call the GitHub API as some user.

    Uses `gh api user` rather than `gh auth status` because the latter
    reports a stricter "invalid token" failure for tokens that DO work
    for actual operations (`gh secret set`, repo writes, etc.) — most
    commonly fine-grained PATs in $GITHUB_TOKEN. `gh api user` succeeds
    whenever the token can perform an authenticated read.
    """
    if not _gh_available():
        return False
    return subprocess.run(
        ["gh", "api", "user", "--silent"],
        capture_output=True, text=True,
    ).returncode == 0


def _gh_api_json(args: list[str]) -> dict:
    """Run `gh api ...`, return parsed JSON. Raises ClickException on failure."""
    result = subprocess.run(
        ["gh", "api", *args],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        raise click.ClickException(
            f"GitHub API call failed ({' '.join(args[:2])}): "
            f"{result.stderr.strip() or result.stdout.strip()}"
        )
    try:
        return json.loads(result.stdout) if result.stdout.strip() else {}
    except json.JSONDecodeError:
        return {}


def _gh_default_branch(repo: str) -> str:
    """Return the repo's default branch via `gh api`."""
    info = _gh_api_json([f"/repos/{repo}"])
    return info.get("default_branch") or "main"


def _gh_branch_exists(repo: str, branch: str) -> bool:
    """Return True if `branch` already exists on `repo`."""
    result = subprocess.run(
        ["gh", "api", f"/repos/{repo}/branches/{branch}", "--silent"],
        capture_output=True, text=True,
    )
    return result.returncode == 0


def _gh_get_branch_sha(repo: str, branch: str) -> str:
    """Get the commit SHA at the tip of `branch`."""
    ref = _gh_api_json([f"/repos/{repo}/git/ref/heads/{branch}"])
    sha = ref.get("object", {}).get("sha")
    if not sha:
        raise click.ClickException(
            f"could not resolve SHA for {repo}@{branch}: {ref}"
        )
    return sha


def _gh_create_branch(repo: str, branch: str, from_sha: str) -> None:
    """Create a new branch ref pointing at `from_sha`."""
    _gh_api_json([
        "-X", "POST",
        f"/repos/{repo}/git/refs",
        "-f", f"ref=refs/heads/{branch}",
        "-f", f"sha={from_sha}",
    ])


def _gh_delete_branch(repo: str, branch: str) -> None:
    """Delete a branch ref. Best-effort; logs on failure."""
    result = subprocess.run(
        ["gh", "api", "-X", "DELETE",
         f"/repos/{repo}/git/refs/heads/{branch}", "--silent"],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        logger.warning(
            "rollback: failed to delete branch %s on %s: %s",
            branch, repo, result.stderr.strip(),
        )


def _gh_put_file(
    repo: str, branch: str, path: str, content: str, commit_message: str,
) -> None:
    """Create a file on `branch` via the contents API."""
    encoded = base64.b64encode(content.encode("utf-8")).decode("ascii")
    _gh_api_json([
        "-X", "PUT",
        f"/repos/{repo}/contents/{path}",
        "-f", f"message={commit_message}",
        "-f", f"content={encoded}",
        "-f", f"branch={branch}",
    ])


def _gh_open_pr(
    repo: str, head: str, base: str, title: str, body: str, draft: bool = True,
) -> tuple[str, int]:
    """Open a pull request. Returns (html_url, number)."""
    args = [
        "-X", "POST",
        f"/repos/{repo}/pulls",
        "-f", f"title={title}",
        "-f", f"head={head}",
        "-f", f"base={base}",
        "-f", f"body={body}",
        "-F", f"draft={'true' if draft else 'false'}",
    ]
    pr = _gh_api_json(args)
    return pr["html_url"], pr["number"]


def _gh_close_pr(repo: str, number: int) -> None:
    """Close a PR. Best-effort rollback path; logs on failure."""
    result = subprocess.run(
        ["gh", "api", "-X", "PATCH",
         f"/repos/{repo}/pulls/{number}", "-f", "state=closed", "--silent"],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        logger.warning(
            "rollback: failed to close PR #%s on %s: %s",
            number, repo, result.stderr.strip(),
        )


def _gh_set_secret(repo: str, name: str, value: str) -> None:
    """Set a repo secret via `gh secret set`. Value goes through stdin —
    never argv, never any log line. `gh` does libsodium sealed-box
    encryption client-side.

    On failure (most common cause: caller's token lacks `actions:secrets`
    admin scope on the repo), surfaces a message that explicitly names
    the required scope so the operator can fix gh auth and retry.
    """
    result = subprocess.run(
        ["gh", "secret", "set", name, "--repo", repo],
        input=value, text=True, capture_output=True,
    )
    if result.returncode != 0:
        stderr = result.stderr.strip()
        hint = ""
        if "403" in stderr or "permission" in stderr.lower():
            hint = (
                f"\n  Your gh token likely lacks admin scope on {repo}. "
                f"Re-authenticate via `gh auth login` and select the repo's "
                f"owner, or use a PAT with `repo` + `workflow` scopes."
            )
        raise click.ClickException(
            f"failed to set secret {name!r} on {repo}: {stderr}{hint}"
        )


# ─── template rendering ────────────────────────────────────────────────────

def _render_workflow(interest_id: str) -> str:
    """Load the bundled workflow template and substitute the interest_id.

    The template lives alongside this module at
    remyxai/cli/templates/outrider.yml. Substitution is a single
    string replace — no Jinja, no extra deps.
    """
    text = (
        resources.files("remyxai.cli")
        .joinpath("templates/outrider.yml")
        .read_text(encoding="utf-8")
    )
    return text.replace("__INTEREST_ID__", interest_id)


# ─── main action handler ───────────────────────────────────────────────────

def handle_outrider_init(
    repo: Optional[str],
    interest_id: Optional[str],
    auto_interest: bool,
    branch_name: str,
    skip_confirm: bool,
    dry_run: bool,
) -> None:
    """Install Outrider on `repo` (or detected from CWD).

    All mutations go through the GitHub API; the operator's local
    working tree is never touched. On any post-mutation failure, the
    branch and PR are rolled back. Secrets are set LAST and are not
    rolled back (we can't safely undo a `gh secret set` upsert without
    losing pre-existing data).
    """

    if interest_id and auto_interest:
        raise click.UsageError(
            "--interest and --auto-interest are mutually exclusive."
        )

    # ── 1. Resolve target repo ────────────────────────────────────────
    if not repo:
        repo = _detect_github_repo_from_cwd()
    if not repo:
        raise click.ClickException(
            "no repo specified and could not detect from CWD. "
            "Pass --repo owner/name."
        )
    if not re.match(r"^[\w.-]+/[\w.-]+$", repo):
        raise click.UsageError(f"--repo must be owner/name, got: {repo!r}")
    click.echo(f"Target repo: {repo}")

    # ── 2. Verify gh ──────────────────────────────────────────────────
    if not _gh_available():
        raise click.ClickException(
            "`gh` (GitHub CLI) is not installed. Install from "
            "https://cli.github.com and re-run."
        )
    if not _gh_authenticated():
        raise click.ClickException(
            "`gh` cannot authenticate. Run `gh auth login` or set a "
            "valid $GITHUB_TOKEN, then re-run."
        )

    # ── 3. Default branch (server-side, not from CWD) ─────────────────
    default_branch = _gh_default_branch(repo)
    click.echo(f"Default branch: {default_branch}")

    # ── 4. REMYXAI_API_KEY ────────────────────────────────────────────
    remyxai_key = os.environ.get("REMYXAI_API_KEY") or click.prompt(
        "REMYXAI_API_KEY (from engine.remyx.ai Settings)",
        hide_input=True,
    )
    if not remyxai_key.strip():
        raise click.ClickException("REMYXAI_API_KEY is required.")

    # ── 5. Resolve interest_id (validate UUID) ────────────────────────
    resolved_interest = _resolve_interest_id(
        interest_id=interest_id,
        auto_interest=auto_interest,
        repo=repo,
        remyxai_key=remyxai_key,
    )

    # ── 6. ANTHROPIC_API_KEY ──────────────────────────────────────────
    anthropic_key = os.environ.get("ANTHROPIC_API_KEY") or click.prompt(
        "ANTHROPIC_API_KEY (from console.anthropic.com)",
        hide_input=True,
    )
    if not anthropic_key.strip():
        raise click.ClickException("ANTHROPIC_API_KEY is required.")

    # ── 7. Render workflow + plan summary ─────────────────────────────
    workflow_content = _render_workflow(resolved_interest)

    click.echo("")
    click.echo("Plan:")
    click.echo(f"  - Create branch     {branch_name!r} (from {default_branch}) on {repo}")
    click.echo(f"  - PUT               {WORKFLOW_PATH} (interest_id: {resolved_interest})")
    click.echo(f"  - Open draft PR     against {default_branch}")
    click.echo(f"  - Set secret        REMYX_API_KEY")
    click.echo(f"  - Set secret        ANTHROPIC_API_KEY")
    click.echo("")

    if dry_run:
        click.echo("--- rendered workflow ---")
        click.echo(workflow_content)
        click.echo("--- end rendered workflow ---")
        click.echo("")
        click.secho("dry-run: no mutations performed.", fg="yellow")
        return

    if not skip_confirm:
        # Default `False` — the operator must affirmatively type 'y'.
        # Repo secrets are non-undoable rotations; better to default to
        # opt-in than risk accidental Enter-pressing.
        click.confirm("Proceed?", abort=True, default=False)

    # ── 8. Idempotency: bail if branch already exists ─────────────────
    if _gh_branch_exists(repo, branch_name):
        raise click.ClickException(
            f"branch {branch_name!r} already exists on {repo}. "
            f"Delete it (`gh api -X DELETE /repos/{repo}/git/refs/"
            f"heads/{branch_name}`) or pass `--branch <other-name>`."
        )

    # ── 9. Execute — reversible mutations first, secrets last ─────────
    pr_number: Optional[int] = None
    branch_created = False
    try:
        # 9a. Branch from default_branch HEAD
        base_sha = _gh_get_branch_sha(repo, default_branch)
        _gh_create_branch(repo, branch_name, base_sha)
        branch_created = True
        click.echo(f"✓ Created branch {branch_name} (from {default_branch}@{base_sha[:8]})")

        # 9b. PUT the workflow file on the new branch
        _gh_put_file(
            repo=repo,
            branch=branch_name,
            path=WORKFLOW_PATH,
            content=workflow_content,
            commit_message=(
                "Install Outrider — weekly arXiv → draft PR scout\n\n"
                "Generated by `remyxai outrider init`."
            ),
        )
        click.echo(f"✓ Wrote {WORKFLOW_PATH}")

        # 9c. Open the PR
        pr_url, pr_number = _gh_open_pr(
            repo=repo,
            head=branch_name,
            base=default_branch,
            title=PR_TITLE,
            body=PR_BODY_TEMPLATE.format(interest_id=resolved_interest),
            draft=True,
        )
        click.echo(f"✓ Opened PR: {pr_url}")

        # 9d. Set secrets LAST. A failure here does not roll back the
        # branch/PR — those are reviewable and customer-deletable
        # without operational risk. The branch + PR being durable also
        # means the operator can investigate the failure with full
        # context.
        _gh_set_secret(repo, "REMYX_API_KEY", remyxai_key)
        click.echo(f"✓ Set REMYX_API_KEY on {repo}")
        _gh_set_secret(repo, "ANTHROPIC_API_KEY", anthropic_key)
        click.echo(f"✓ Set ANTHROPIC_API_KEY on {repo}")

    except Exception as e:
        # Rollback in reverse order. Only the branch + PR are reversible;
        # secrets are upserts and we don't have the pre-existing values.
        if pr_number is not None:
            click.echo(f"  ↩ rolling back: closing PR #{pr_number}", err=True)
            _gh_close_pr(repo, pr_number)
        if branch_created:
            click.echo(f"  ↩ rolling back: deleting branch {branch_name}", err=True)
            _gh_delete_branch(repo, branch_name)
        # Re-raise so click surfaces the error + exit code.
        if isinstance(e, click.ClickException):
            raise
        raise click.ClickException(f"install failed: {e}")

    # ── 10. Done ──────────────────────────────────────────────────────
    click.echo("")
    click.secho("✓ Outrider is ready.", fg="green", bold=True)
    click.echo(f"  PR:        {pr_url}")
    click.echo(f"  Schedule:  Mondays 14:00 UTC (edit the cron in {WORKFLOW_PATH})")
    click.echo(f"  Manual:    gh workflow run outrider.yml --repo {repo}")


def _resolve_interest_id(
    interest_id: Optional[str],
    auto_interest: bool,
    repo: str,
    remyxai_key: str,
) -> str:
    """Resolve the interest_id via the flag, auto-create, or prompt path.

    All three paths produce a string that's validated as a UUID before
    being substituted into the workflow YAML.
    """
    if interest_id:
        if not UUID_RE.match(interest_id):
            raise click.UsageError(
                f"--interest must be a UUID, got: {interest_id!r}"
            )
        # Stronger: probe the engine to confirm the interest exists.
        # If the user typed a UUID that doesn't resolve, we fail fast
        # rather than silently writing a workflow that no-ops weekly.
        try:
            get_interest(interest_id, api_key=remyxai_key)
        except Exception as e:
            raise click.ClickException(
                f"interest {interest_id} could not be fetched from "
                f"engine.remyx.ai: {e}. Check the UUID and your "
                f"REMYXAI_API_KEY."
            )
        return interest_id

    if auto_interest:
        click.echo(
            "Creating a Research Interest from this repo's commit history "
            "(may take 30-90 seconds)…"
        )
        repo_url = f"https://github.com/{repo}"
        try:
            created = create_interest(
                name=repo.split("/")[-1],
                context=repo_url,
                daily_count=3,
                is_active=True,
                api_key=remyxai_key,
            )
            new_id = created.get("id")
            if not new_id or not UUID_RE.match(new_id):
                raise click.ClickException(
                    f"interest creation did not return a UUID: {created}"
                )
            click.echo(f"✓ Created interest: {new_id}")
            return new_id
        except click.ClickException:
            raise
        except Exception as e:
            raise click.ClickException(
                f"interest creation failed: {e}\n"
                f"  Fall back to manual: create an interest at "
                f"engine.remyx.ai and re-run with --interest <uuid>."
            )

    # Interactive prompt path
    typed = click.prompt(
        "Remyx interest UUID (from engine.remyx.ai)"
    ).strip()
    if not UUID_RE.match(typed):
        raise click.UsageError(
            f"interest UUID is malformed: {typed!r}"
        )
    return typed
