"""
CLI action handlers for Outrider lifecycle management.

`remyxai outrider init` installs the Outrider GitHub Action on the
current repo:
  1. Detect git repo + GitHub remote + default branch
  2. Verify `gh` is installed and authenticated
  3. Resolve the Remyx ResearchInterest (provided, auto-created, or prompted)
  4. Set REMYX_API_KEY + ANTHROPIC_API_KEY repo secrets via `gh secret set`
  5. Write .github/workflows/outrider.yml on a new branch
  6. Open a draft PR for the customer to review

Alternative to the GitHub-App-based install flow (engine.remyx.ai's
provision-action endpoint) for orgs that can't or won't grant a
third-party App access. Uses the customer's existing `gh` auth.
"""
from __future__ import annotations

import logging
import os
import re
import shutil
import subprocess
from importlib import resources
from pathlib import Path
from typing import Optional

import click

from remyxai.api.interests import create_interest

logger = logging.getLogger(__name__)

DEFAULT_BRANCH_NAME = "install-outrider"
WORKFLOW_PATH = ".github/workflows/outrider.yml"
PR_TITLE = "Install Outrider — weekly arXiv → draft PR scout"
PR_BODY_TEMPLATE = """\
Adds [remyxai/outrider](https://github.com/remyxai/outrider) on a weekly Monday-14:00-UTC schedule (with `workflow_dispatch` for manual triggering). Outrider queries engine.remyx.ai for a paper recommendation against this repo's ResearchInterest, then opens a draft PR (or Issue) wiring the paper's contribution into an existing call site.

**What was installed:**

- `.github/workflows/outrider.yml` — weekly cron + manual dispatch
- Repo secret `REMYX_API_KEY` — engine.remyx.ai token (set by the CLI)
- Repo secret `ANTHROPIC_API_KEY` — Anthropic console token (set by the CLI)

**Research interest**: `{interest_id}`

Generated by `remyxai outrider init`. Review the workflow, merge when ready.
"""


# ─── git helpers (shell out to `git`) ──────────────────────────────────────

def _find_git_root(start: Optional[Path] = None) -> Optional[Path]:
    cur = (start or Path.cwd()).resolve()
    for p in [cur, *cur.parents]:
        if (p / ".git").is_dir():
            return p
    return None


def _detect_github_repo(workdir: Path) -> Optional[str]:
    """Parse the origin remote URL and return 'owner/repo' or None."""
    try:
        out = subprocess.check_output(
            ["git", "-C", str(workdir), "remote", "get-url", "origin"],
            text=True, stderr=subprocess.DEVNULL,
        ).strip()
    except subprocess.CalledProcessError:
        return None
    url = out[:-4] if out.endswith(".git") else out
    m = re.match(r"git@github\.com:([\w.-]+/[\w.-]+)$", url)
    if m:
        return m.group(1)
    m = re.match(r"https?://github\.com/([\w.-]+/[\w.-]+)$", url)
    if m:
        return m.group(1)
    return None


def _detect_default_branch(workdir: Path) -> str:
    """Prefer origin/HEAD; fall back to 'main' if unset."""
    try:
        out = subprocess.check_output(
            ["git", "-C", str(workdir), "symbolic-ref",
             "refs/remotes/origin/HEAD"],
            text=True, stderr=subprocess.DEVNULL,
        ).strip()
        return out.rsplit("/", 1)[-1]
    except subprocess.CalledProcessError:
        return "main"


# ─── gh helpers (shell out to `gh`) ────────────────────────────────────────

def _gh_available() -> bool:
    return shutil.which("gh") is not None


def _gh_authenticated() -> bool:
    """Return True if `gh` can call the GitHub API as some user.

    Uses `gh api user` rather than `gh auth status` because the latter
    reports a stricter "invalid token" failure for tokens that DO work
    for actual operations (`gh secret set`, `gh pr create`, etc.) — most
    commonly fine-grained PATs in $GITHUB_TOKEN. `gh api user` succeeds
    whenever the token can perform an authenticated read, which is the
    operational equivalent of what this pre-check actually wants to know.
    """
    if not _gh_available():
        return False
    return subprocess.run(
        ["gh", "api", "user", "--silent"],
        capture_output=True, text=True,
    ).returncode == 0


def _gh_set_secret(repo: str, name: str, value: str) -> None:
    """Set a repo secret via `gh secret set`. Value goes through stdin —
    never argv, never any log line. `gh` does libsodium sealed-box
    encryption client-side."""
    result = subprocess.run(
        ["gh", "secret", "set", name, "--repo", repo],
        input=value, text=True, capture_output=True,
    )
    if result.returncode != 0:
        raise click.ClickException(
            f"failed to set secret {name!r} on {repo}: "
            f"{result.stderr.strip()}"
        )


def _gh_create_pr(
    repo: str, head: str, base: str, title: str, body: str, draft: bool = True,
) -> str:
    cmd = [
        "gh", "pr", "create",
        "--repo", repo, "--head", head, "--base", base,
        "--title", title, "--body", body,
    ]
    if draft:
        cmd.append("--draft")
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise click.ClickException(f"failed to open PR: {result.stderr.strip()}")
    return result.stdout.strip().splitlines()[-1]


# ─── template rendering ────────────────────────────────────────────────────

def _render_workflow(interest_id: str) -> str:
    """Load the bundled workflow template and substitute the interest_id.

    The template lives alongside this module at
    remyxai/cli/templates/outrider.yml. Substitution is a single
    string replace — no Jinja, no extra deps.
    """
    text = (
        resources.files("remyxai.cli")
        .joinpath("templates/outrider.yml")
        .read_text(encoding="utf-8")
    )
    return text.replace("__INTEREST_ID__", interest_id)


# ─── main action handler ───────────────────────────────────────────────────

def handle_outrider_init(
    interest_id: Optional[str],
    auto_interest: bool,
    branch_name: str,
    skip_confirm: bool,
) -> None:
    """Install Outrider on the current repo. Called from
    commands.outrider_init in commands.py."""

    if interest_id and auto_interest:
        raise click.UsageError(
            "--interest and --auto-interest are mutually exclusive."
        )

    # ── 1. Detect repo ────────────────────────────────────────────────
    workdir = _find_git_root()
    if workdir is None:
        raise click.ClickException("Not inside a git repository.")

    repo = _detect_github_repo(workdir)
    if repo is None:
        raise click.ClickException(
            "Origin remote isn't a github.com URL. Outrider requires a "
            "GitHub-hosted repo."
        )

    default_branch = _detect_default_branch(workdir)
    click.echo(f"Detected repo: {repo} (default branch: {default_branch})")

    # ── 2. Verify gh ──────────────────────────────────────────────────
    if not _gh_available():
        raise click.ClickException(
            "`gh` (GitHub CLI) is not installed. Install from "
            "https://cli.github.com and re-run."
        )
    if not _gh_authenticated():
        raise click.ClickException(
            "`gh` is not authenticated. Run `gh auth login` and re-run."
        )

    # ── 3. REMYXAI_API_KEY ────────────────────────────────────────────
    remyxai_key = os.environ.get("REMYXAI_API_KEY") or click.prompt(
        "REMYXAI_API_KEY (from engine.remyx.ai Settings)",
        hide_input=True,
    )
    if not remyxai_key.strip():
        raise click.ClickException("REMYXAI_API_KEY is required.")

    # ── 4. interest_id ────────────────────────────────────────────────
    if interest_id:
        resolved_interest = interest_id
    elif auto_interest:
        click.echo(
            "Creating a Research Interest from this repo's commit history "
            "(may take 30-90 seconds)…"
        )
        repo_url = f"https://github.com/{repo}"
        try:
            # The engine accepts a GitHub URL in the `context` field and
            # scrapes the repo + generates an embedding server-side. The
            # repo name doubles as the human-readable label.
            created = create_interest(
                name=repo.split("/")[-1],
                context=repo_url,
                daily_count=3,
                is_active=True,
                api_key=remyxai_key,
            )
            resolved_interest = created.get("id")
            if not resolved_interest:
                raise click.ClickException(
                    f"interest creation did not return an id: {created}"
                )
            click.echo(f"✓ Created interest: {resolved_interest}")
        except Exception as e:
            raise click.ClickException(
                f"Interest creation failed: {e}\n"
                f"  Fall back to manual: create an interest at "
                f"engine.remyx.ai and re-run with --interest <uuid>."
            )
    else:
        resolved_interest = click.prompt(
            "Remyx interest UUID (from engine.remyx.ai)"
        ).strip()
        if not resolved_interest:
            raise click.ClickException("Interest UUID is required.")

    # ── 5. ANTHROPIC_API_KEY ──────────────────────────────────────────
    anthropic_key = os.environ.get("ANTHROPIC_API_KEY") or click.prompt(
        "ANTHROPIC_API_KEY (from console.anthropic.com)",
        hide_input=True,
    )
    if not anthropic_key.strip():
        raise click.ClickException("ANTHROPIC_API_KEY is required.")

    # ── 6. Confirm ────────────────────────────────────────────────────
    click.echo("")
    click.echo("About to:")
    click.echo(f"  - Create branch {branch_name!r} from {default_branch}")
    click.echo(f"  - Write {WORKFLOW_PATH}")
    click.echo(f"  - Set 2 repo secrets via `gh secret set`")
    click.echo(f"  - Open a draft PR against {default_branch}")
    click.echo("")
    if not skip_confirm:
        click.confirm("Proceed?", abort=True, default=True)

    # ── 7. Execute ────────────────────────────────────────────────────
    result = subprocess.run(
        ["git", "-C", str(workdir), "checkout", "-b", branch_name],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        raise click.ClickException(
            f"failed to create branch {branch_name!r}: {result.stderr.strip()}"
        )
    click.echo(f"✓ Created branch {branch_name}")

    workflow_path = workdir / WORKFLOW_PATH
    workflow_path.parent.mkdir(parents=True, exist_ok=True)
    workflow_path.write_text(_render_workflow(resolved_interest))
    click.echo(f"✓ Wrote {WORKFLOW_PATH}")

    # Set secrets BEFORE committing — if either fails we haven't polluted
    # the repo's history yet (the branch is cheap to delete).
    _gh_set_secret(repo, "REMYX_API_KEY", remyxai_key)
    click.echo(f"✓ Set REMYX_API_KEY on {repo}")
    _gh_set_secret(repo, "ANTHROPIC_API_KEY", anthropic_key)
    click.echo(f"✓ Set ANTHROPIC_API_KEY on {repo}")

    # Commit + push + PR.
    subprocess.run(
        ["git", "-C", str(workdir), "add", WORKFLOW_PATH], check=True,
    )
    subprocess.run(
        ["git", "-C", str(workdir), "commit", "-m",
         "Install Outrider — weekly arXiv → draft PR scout\n\n"
         "Generated by `remyxai outrider init`."],
        check=True,
    )
    subprocess.run(
        ["git", "-C", str(workdir), "push", "-u", "origin", branch_name],
        check=True,
    )

    pr_url = _gh_create_pr(
        repo=repo, head=branch_name, base=default_branch,
        title=PR_TITLE,
        body=PR_BODY_TEMPLATE.format(interest_id=resolved_interest),
        draft=True,
    )

    click.echo("")
    click.secho("✓ Outrider is ready.", fg="green", bold=True)
    click.echo(f"  PR:        {pr_url}")
    click.echo(f"  Schedule:  Mondays 14:00 UTC (edit the cron in {WORKFLOW_PATH})")
    click.echo(f"  Manual:    gh workflow run outrider.yml --repo {repo}")
